### PR TITLE
init project + setup Sun*CI

### PR DESCRIPTION
**Pull request by kdmachine**
Screenshot from 2022-01-17 23-08-03

### CODE REVIEW

**Comment by kdmachine** [comment]
ready

**Comment by kdmachine** [comment]
ready

**Comment by kdmachine** [comment]
ready

**Comment by kdmachine** [comment]
ready

**Review by ghost — COMMENTED** [review]
self review lại

**Comment by kdmachine** [comment]
ready

**Comment by kdmachine** [comment]
ready

**Comment by kdmachine** [comment]
ready

**Pull request closed without merging**
